spring.application.name=task-tracker-api

spring.datasource.url=jdbc:postgresql://localhost:5432/task_tracker
spring.datasource.username=postgres
spring.datasource.password=tiger1905

spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
