spring.application.name=task-tracker-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tiger1905}

spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=${JWT_SECRET:myVeryLongSecretKeyThatShouldBeStoredOutside}
jwt.expiration=${JWT_EXPIRATION:3600}
